services:
    EzSystems\EzPlatformAdminUi\Tab\ContentType\:
        resource: "../../../lib/Tab/ContentType/*"
        parent: EzSystems\EzPlatformAdminUi\Tab\AbstractTab
        public: true
        tags:
            - { name: ezplatform.tab, group: content-type }
